[project]
name = "ccn-template"
version = "0.0.1"
authors = [
  { name="Billy Broderick", email="author@example.com" },
]
description = "Template for CCN package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/flatironinstitute/ccn-template"

[project.optional-dependencies]
docs = [
    "mkdocs",
    "mkdocstrings[python]",
    "mkdocs_section_index",
    "mkdocs_gen_files",
    "mkdocs_literate_nav",
    "mkdocs-gallery",
]
