# Define the build system requirements for the project.
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ccn-template"
version = "0.0.1"
authors = [
  { name="Billy Broderick", email="author@example.com" },
]
description = "Template for CCN package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
# Optional dependencies for documentation [docs] and testing/linting [dev]:
[project.optional-dependencies]
docs = [
    'mkdocs',
    'mkdocstrings[python]',
    'mkdocs_section_index',
    'mkdocs_gen_files',
    'mkdocs_literate_nav',
    'mkdocs-gallery',
    'pillow'
]
dev = [
    "black",                        # Code formatter
    "isort",                        # Import sorter
    "pip-tools",                    # Dependency management
    "pytest",                       # Testing framework
    "flake8",                       # Code linter
    "coverage",                     # Test coverage measurement
    "pytest-cov",                   # Test coverage plugin for pytest
]

[project.urls]
"Homepage" = "https://github.com/flatironinstitute/ccn-template"

# Configure the package discovery behavior for setuptools
[tool.setuptools.packages.find]
where = ["src"] #  specifies the root directory to start searching for packages
include = ["ccn_template"] # specifies patterns for including specific packages or modules

# addopts: Additional command-line options for pytest.
[tool.pytest.ini_options]
addopts = "--cov=ccn_template"
testpaths = ["tests"]
